### ISSUE TITLE
A.1 Cuenta de usuario

### ISSUE THREAD

**Issue by brunocalmels** [MacherIT/fiblo#1]
Un usuario debe poder crearse una cuenta con usuario y contraseña, y recuperarla en caso de habérsela olvidado.

**Comment by ivaneidel** [comment]
Hasta ahora está, creería yo, todo resuelto.
Toda la funcionalidad está reducida a componentes que son autónomos, faltan algunos detalles de manejo de errores (cuenta duplicada, failed login, etc.) pero la general está.

El frontend en VueJS interactúa con el backend en ExpressJS + Sequelize por medio de requests http

![image](https://user-images.githubusercontent.com/9538260/45905147-bfddef00-bdc5-11e8-86e0-10c0fd8ca619.png)

---------

Los usuarios no se enlazan en ningún momento con nada de la blockchain... si no entendí mal, para este issue, no hacía falta eso, cierto?

**Comment by brunocalmels** [comment]
Está bien, en este momento no tenía nada que ver con blockchain.
