### ISSUE TITLE
B.1 Creación de proyectos

### ISSUE THREAD

**Issue by brunocalmels** [MacherIT/fiblo#2]
Un usuario puede cargar su proyecto/sociedad, con los siguientes atributos:
- Nombre, domicilio, datos de contacto.
- Datos de los emprendedores
- Monto a recaudar
- Monto máximo de sobresuscripción (monto por sobre el deseado)
- Área/sector del proyecto

**Comment by ivaneidel** [comment]
El modelo de datos y el formulario de carga estan listos, no hay asociación alguna todavía con tokens o contratos, solo la base de sistema y la intefaz

![image](https://user-images.githubusercontent.com/9538260/46022830-bdc3ab00-c0b9-11e8-85e8-b7522b45de98.png)

![image](https://user-images.githubusercontent.com/9538260/46022800-abe20800-c0b9-11e8-8c57-e4c2f8b3caac.png)

**Comment by brunocalmels** [comment]
Great!

**Comment by brunocalmels** [comment]
Está mergeado ya?

**Comment by ivaneidel** [comment]
Nop, ahora lo hago ;)

Estoy haciendo pull requests para que los apruebes (así seguimos el flow correcto)

**Comment by brunocalmels** [comment]
Ya estaban mergeados.
