### ISSUE TITLE
C.1 Listar proyectos

### ISSUE THREAD

**Issue by brunocalmels** [MacherIT/fiblo#3]
Un usuario debe poder navegar por entre los proyectos disponibles para invertir.

**Comment by ivaneidel** [comment]
Sin interfaz, está completo:

Index:
![image](https://user-images.githubusercontent.com/9538260/46107523-f47cec80-c1b1-11e8-8ebd-8b885a2775f1.png)
---------
Show:
![image](https://user-images.githubusercontent.com/9538260/46107540-0199db80-c1b2-11e8-8638-edf0c7c624aa.png)

**Comment by brunocalmels** [comment]
Una cabecerita para la tabla del Index, no?

**Comment by ivaneidel** [comment]
Sisi, estaba en otro issue:

![](https://user-images.githubusercontent.com/9538260/46418601-7add8500-c702-11e8-8d8e-f7d139febbd1.png)

**Comment by brunocalmels** [comment]
Ahhhhh, ta bien, ta bien. Cierro el issue entonces!
