### ISSUE TITLE
C.2 Buscar/filtrar proyectos 

### ISSUE THREAD

**Issue by brunocalmels** [MacherIT/fiblo#4]
Un usuario debe poder buscar un proyecto por cualquiera de los siguientes atributos:
- Nombre de la sociedad o emprendedores
- Ciudad o región
- Categoría
- Monto de inversión mínima
- Monto de inversión máxima

**Comment by ivaneidel** [comment]
En cuanto a ciudad o región y a categoría, no estaban como tales en B.1, debería agregarlas al modelo de proyecto?

**Comment by brunocalmels** [comment]
Yaaa, yaaaa, lo que haga falta, mi amigo!

**Comment by ivaneidel** [comment]
Oka oka, se añade

**Comment by ivaneidel** [comment]
Deberíamos estar con esto ;)

![image](https://user-images.githubusercontent.com/9538260/46418624-8f218200-c702-11e8-835b-eeaca3c81a38.png)
---------
![image](https://user-images.githubusercontent.com/9538260/46418601-7add8500-c702-11e8-8d8e-f7d139febbd1.png)

**Comment by brunocalmels** [comment]
Perfect! :+1:
